# VaultSyncMySQL Configuration

# Database settings
database:
  host: localhost
  port: 3306
  name: minecraft
  username: root
  password: password
  table: player_money

# Synchronization settings
# Choose synchronization method:
# - "time" - synchronize at regular intervals
# - "events" - synchronize on player join/quit events
sync-method: "time"

# Synchronization interval in minutes (only used if sync-method is "time")
sync-interval-minutes: 10

# Force full synchronization of all players (online and offline) on plugin start
force-full-sync: false

# Immediately sync new players when they join for the first time
sync-new-players-immediately: true

# Enable debug mode (more verbose logging)
debug-mode: false
